import { StyleSheet } from "react-native";

export const depositStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#05012B",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
    paddingTop: 100,
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 50,
    zIndex: 1000,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: "#05012B",
  },
  backButton: { padding: 4 },
  screenTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  historyButton: { padding: 4 },
  historyButtonText: {
    fontSize: 14,
    color: "#7AFEC3",
  },
  // Balance card
  balanceCard: {
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 16,
    overflow: "hidden",
  },
  balanceCardContent: {
    padding: 20,
    paddingBottom: 16,
  },
  balanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  balanceHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  walletEmoji: { fontSize: 18 },
  balanceLabel: {
    fontSize: 15,
    color: "#fff",
    fontWeight: "600",
  },
  balanceAmount: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 20,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardNumber: {
    fontSize: 16,
    color: "rgba(255,255,255,0.7)",
    letterSpacing: 4,
  },
  // Method tabs
  methodsSection: {
    marginHorizontal: 16,
    marginTop: 20,
  },
  methodsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  methodButton: {
    width: "22.5%",
    aspectRatio: 1,
    backgroundColor: "#0D1B4B",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    padding: 8,
    position: "relative",
  },
  methodButtonActive: { backgroundColor: "#7AFEC3" },
  methodIconContainer: {
    marginBottom: 6,
    alignItems: "center",
  },
  methodIconText: {
    fontSize: 10,
    color: "#7AFEC3",
    fontWeight: "700",
    textAlign: "center",
  },
  methodIconTextActive: { color: "#05012B" },
  methodLabel: {
    fontSize: 11,
    color: "#fff",
    textAlign: "center",
    fontWeight: "500",
  },
  methodLabelActive: {
    color: "#05012B",
    fontWeight: "700",
  },
  bonusBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#FF4D00",
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  bonusText: {
    fontSize: 9,
    color: "#fff",
    fontWeight: "bold",
  },
  // Shared section
  section: {
    marginHorizontal: 16,
    marginTop: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionIconImg: {
    width: 22,
    height: 22,
    borderRadius: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  // Channel selector
  channelGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  channelCard: {
    width: "47.5%",
    backgroundColor: "#0D1B4B",
    borderRadius: 12,
    padding: 14,
  },
  channelCardActive: { backgroundColor: "#7AFEC3" },
  channelLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 4,
  },
  channelLabelActive: { color: "#05012B" },
  channelBalance: {
    fontSize: 13,
    color: "#92A8E3",
  },
  channelBalanceActive: { color: "#05012B" },
  usdtChannelCard: {
    width: "100%",
    backgroundColor: "#7AFEC3",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  usdtChannelIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#26A17B",
    alignItems: "center",
    justifyContent: "center",
  },
  usdtIconText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  // Amount selector
  depositAmountInner: {
    backgroundColor: "#0D1B4B",
    borderRadius: 14,
    padding: 16,
  },
  amountGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  amountButton: {
    width: "30.5%",
    backgroundColor: "#05012B",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  amountButtonActive: {
    borderWidth: 1,
    borderColor: "#7AFEC3",
  },
  amountRupee: {
    fontSize: 13,
    color: "#7AFEC3",
    fontWeight: "600",
  },
  amountValue: {
    fontSize: 13,
    color: "#7AFEC3",
    fontWeight: "600",
  },
  usdtAmountIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#26A17B",
    alignItems: "center",
    justifyContent: "center",
  },
  usdtAmountIconText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#fff",
  },
  amountInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0D1B4B",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
  },
  inputDivider: {
    width: 1,
    height: 20,
    backgroundColor: "#92A8E3",
  },
  currencySymbol: {
    fontSize: 18,
    fontWeight: "700",
    color: "#7AFEC3",
  },
  amountInput: {
    flex: 1,
    fontSize: 15,
    color: "#92A8E3",
  },
  usdtInputIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#26A17B",
    alignItems: "center",
    justifyContent: "center",
  },
  usdtInputIconText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#fff",
  },
  // Instructions
  instructionsBox: {
    backgroundColor: "#0D1B4B",
    borderRadius: 14,
    padding: 16,
  },
  instructionsList: {
    gap: 14,
    marginTop: 4,
  },
  instructionItem: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  instructionBullet: {
    fontSize: 11,
    color: "#7AFEC3",
    marginTop: 3,
  },
  instructionText: {
    flex: 1,
    fontSize: 14,
    color: "#92A8E3",
    lineHeight: 20,
  },
  // History
  emptyState: {
    alignItems: "center",
    paddingVertical: 24,
  },
  emptyImage: {
    width: 160,
    height: 120,
  },
  emptyText: {
    fontSize: 14,
    color: "#92A8E3",
    marginTop: 8,
  },
  // Bottom bar
  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#05012B",
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: "#0D1B4B",
  },
  bottomBarLeft: { flex: 1 },
  rechargeMethodLabel: {
    fontSize: 12,
    color: "#92A8E3",
  },
  rechargeMethodValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#fff",
    marginTop: 2,
  },
  depositButton: {
    backgroundColor: "#7AFEC3",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  depositButtonDisabled: { backgroundColor: "#3A4A6B" },
  depositButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#05012B",
  },
  // ARPay
  arRulesRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0D1B4B",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
  },
  arRulesText: {
    flex: 1,
    fontSize: 14,
    color: "#fff",
  },
  arRulesCheck: {
    fontSize: 14,
    color: "#7AFEC3",
  },
  arNotActivatedRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0D1B4B",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 10,
  },
  arNotActivatedIcon: {
    fontSize: 22,
    color: "#F5A623",
    fontWeight: "bold",
  },
  arNotActivatedText: {
    flex: 1,
    fontSize: 13,
    color: "#fff",
  },
  arActivateBtn: {
    backgroundColor: "#7AFEC3",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  arActivateBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#05012B",
  },
  arInfoCard: {
    backgroundColor: "#0D1B4B",
    borderRadius: 14,
    padding: 16,
  },
  arInfoText: {
    fontSize: 14,
    color: "#fff",
    lineHeight: 22,
    marginBottom: 14,
  },
  arHowToRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  arHowToText: {
    fontSize: 14,
    color: "#fff",
  },
  arFeaturesTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 14,
  },
  arActivateBtnFull: {
    backgroundColor: "#7AFEC3",
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
  },
});
